### ISSUE TITLE
Some beta testing bugs

### ISSUE THREAD

**Issue by emmadesilva** [melasistema/hydephp-layouts-manager#1]
Hey there! This looks like a super promising package. I'm trying it out now, and have found some bugs when trying a fresh install.

---

Following the instructions, it doesn't load the views correctly. It does work if I publish the files though.

```php
InvalidArgumentException
View [vendor.hyde-layouts-manager.layouts.melasistema.post] not found.
```

Make sure to register the view paths the same as for a normal Laravel application: https://laravel.com/docs/11.x/packages#views

You don't need to include "vendor" in the path, just the namespace and Laravel will know to use the published or original file.

---

The header image is a 404: http://localhost:8080/media/hyde-layouts-manager/mixed/melasistema-luca-visciola.jpg
<img width="727" alt="image" src="https://github.com/user-attachments/assets/dbbca3bb-c1e8-41a1-b6ca-3c14b18f9e88" />

It looks like maybe you're not reading from the config?

---

Again, great work on this package, it looks amazing and I can't wait to see what more cool things you cook up! /Caen, creator of HydePHP

**Comment by melasistema** [comment]
Hi @caendesilva ,
My fault, I wasn't using the "namespace" as I should have. Now the views behave as expected.

For the placeholder images, I implemented the creation of a symlink at boot.

For the details, I’ve uploaded the [CHANGELOG](https://github.com/melasistema/hydephp-layouts-manager/blob/master/CHANGELOG.md) 😊

🙏🏻 Thanks again for the support, it's really appreciated!
